### ISSUE TITLE
Upgrade webpack version

### ISSUE THREAD

**Issue by tahini** [chairemobilite/transition#531]
There are problems with webpack 4 and node 17+. See https://github.com/webpack/webpack/issues/14532

Current workaround is to run `export NODE_OPTIONS=--openssl-legacy-provider` before running `yarn build:dev`, but we should upgrade to webpack 5 to have this fixed.

**Comment by millette** [comment]
There are a few options.

[Webpack 5](https://webpack.js.org/blog/2020-10-10-webpack-5-release/) was released 3 years ago. Webpack 6 is not clearly defined, so webpack 5 will be supported for a while.

[Turbopack](https://turbo.build/pack) is used by next.js. It's being developped by the webpack creator as its successor but that doesn't mean it will have a 1:1 correspondance with webpack. It's not going to be compatible. Most importantly, it's not actually released yet, it's only packaged to be used with next.js for the moment.

[Vite](https://vitejs.dev/) is a wrapper for esbuild, rollup and a few more modern tools. Version 4 was released less than a year ago and also provides a fast (hence the name) developper experience.

[Upgrading to webpack 5](https://webpack.js.org/migrate/5/) is the easiest route but it's also somewhat of a dead-end since turbopack is designed to be its successor and vite is still growing in popularity.

Turbopack is not really an option right now and it's hard to tell when it will be generally available.

For the moment, I'll take some time to investigate moving to vite.

**Comment by tahini** [comment]
I would say webpack 5 is the way to go, unless you have new informations with vite: how many projects use it? Are webpack users moving to it massively?

From my experience with re-writes of successors like turbopack, it either works (and is adopted and widely used and there's documentation for the migration), or it fails to see the light of day, so we'll believe it when we see it! Maybe worth leaving an issue to remind us to take a look at it later.
